const fs = require('fs');
const path = require('path');

const menuDir = path.join(__dirname, '..', 'assets', 'menu');
const outFile = path.join(__dirname, '..', 'lib', 'menuImageData.ts');

const files = fs.readdirSync(menuDir).filter(f => /\.(png|jpg)$/i.test(f));

const lines = [];
lines.push('// Auto-generated by scripts/generateBase64Images.js');
lines.push('// Do not edit manually. Run `node scripts/generateBase64Images.js` to regenerate.');
lines.push('');
lines.push('export const menuImageData: Record<string, string> = {');

for (const file of files) {
  const ext = path.extname(file).toLowerCase();
  const mime = ext === '.png' ? 'image/png' : 'image/jpeg';
  const filePath = path.join(menuDir, file);
  const buffer = fs.readFileSync(filePath);
  const base64 = buffer.toString('base64');
  const dataUri = `data:${mime};base64,${base64}`;
  lines.push(`  '${file}': '${dataUri}',`);
}

lines.push('};');
lines.push('');

const content = lines.join('\n');
fs.writeFileSync(outFile, content);

console.log(`Generated ${outFile}`);
console.log(`Images processed: ${files.length}`);
console.log(`File size: ${(Buffer.byteLength(content) / 1024 / 1024).toFixed(1)} MB`);
