import { Asset } from 'expo-asset';

export const menuImages: Record<string, number> = {
  'AN01.png': require('./AN01.png'),
  'AN02.png': require('./AN02.png'),
  'AN03.png': require('./AN03.png'),
  'AN04.jpg': require('./AN04.jpg'),
  'AN05.jpg': require('./AN05.jpg'),
  'AN06.png': require('./AN06.png'),
  'AN07.jpg': require('./AN07.jpg'),
  'AN08.jpg': require('./AN08.jpg'),
  'AN09.png': require('./AN09.png'),
  'AN10.jpg': require('./AN10.jpg'),
  'AN11.png': require('./AN11.png'),
  'AN12.jpg': require('./AN12.jpg'),
  'AN13.png': require('./AN13.png'),
  'AN14.png': require('./AN14.png'),
  'AN15.png': require('./AN15.png'),
  'AN16.png': require('./AN16.png'),
  'AN17.png': require('./AN17.png'),
  'AN18.jpg': require('./AN18.jpg'),
  'BI01.jpg': require('./BI01.jpg'),
  'BI02.jpg': require('./BI02.jpg'),
  'BI03.jpg': require('./BI03.jpg'),
  'BI04.jpg': require('./BI04.jpg'),
  'BI05.jpg': require('./BI05.jpg'),
  'BI06.jpg': require('./BI06.jpg'),
  'BI07.png': require('./BI07.png'),
  'BI08.png': require('./BI08.png'),
  'BI09.jpg': require('./BI09.jpg'),
  'BU01.jpg': require('./BU01.jpg'),
  'BU02.jpg': require('./BU02.jpg'),
  'BV01.jpg': require('./BV01.jpg'),
  'BV02.jpg': require('./BV02.jpg'),
  'BV03.jpg': require('./BV03.jpg'),
  'BV04.png': require('./BV04.png'),
  'BV05.jpg': require('./BV05.jpg'),
  'BV06.jpg': require('./BV06.jpg'),
  'BV07.jpg': require('./BV07.jpg'),
  'BV08.jpg': require('./BV08.jpg'),
  'BV09.jpg': require('./BV09.jpg'),
  'BV10.jpg': require('./BV10.jpg'),
  'BV11.jpg': require('./BV11.jpg'),
  'BV12.jpg': require('./BV12.jpg'),
  'BV13.jpg': require('./BV13.jpg'),
  'BV14.jpg': require('./BV14.jpg'),
  'BV15.png': require('./BV15.png'),
  'BV16.png': require('./BV16.png'),
  'BV17.jpg': require('./BV17.jpg'),
  'BV18.jpg': require('./BV18.jpg'),
  'BV19.jpg': require('./BV19.jpg'),
  'BV20.jpg': require('./BV20.jpg'),
  'KB01.png': require('./KB01.png'),
  'KB07.png': require('./KB07.png'),
  'KB09.png': require('./KB09.png'),
  'MC01.png': require('./MC01.png'),
  'MC04.png': require('./MC04.png'),
  'MC05.png': require('./MC05.png'),
  'MC06.png': require('./MC06.png'),
  'MC07.png': require('./MC07.png'),
  'MC08.jpg': require('./MC08.jpg'),
  'VG01.png': require('./VG01.png'),
  'VG04.png': require('./VG04.png'),
  'VG05.png': require('./VG05.png'),
};

export async function preloadMenuImages(): Promise<void> {
  await Asset.loadAsync(Object.values(menuImages));
}

export function getMenuImage(filename?: string | null): number | undefined {
  if (!filename) return undefined;
  return menuImages[filename.trim()];
}
